apiVersion: v1
kind: Service
metadata:
  name: nginx-lb-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-deployment  # Must match the label in your Nginx Deployment
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the Load Balancer
      targetPort: 80   # Port the Nginx container is listening on

