# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default # Replace with your namespace if different
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # The port your NGINX container is listening on
  selector:
    app: nginx-deployment # This must match the labels on your NGINX pods

